# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tusimple/CLionProjects/cpp_notes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tusimple/CLionProjects/cpp_notes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/tusimple/Downloads/clion-2020.1.1/bin/cmake/linux/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tusimple/CLionProjects/cpp_notes/CMakeFiles /home/tusimple/CLionProjects/cpp_notes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tusimple/CLionProjects/cpp_notes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_notes

# Build rule for target.
cpp_notes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_notes
.PHONY : cpp_notes

# fast build rule for target.
cpp_notes/fast:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/build
.PHONY : cpp_notes/fast

#=============================================================================
# Target rules for targets named Tools

# Build rule for target.
Tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tools
.PHONY : Tools

# fast build rule for target.
Tools/fast:
	$(MAKE) -f tools/CMakeFiles/Tools.dir/build.make tools/CMakeFiles/Tools.dir/build
.PHONY : Tools/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/notes1_stl_types.o: src/notes1_stl_types.cpp.o

.PHONY : src/notes1_stl_types.o

# target to build an object file
src/notes1_stl_types.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes1_stl_types.cpp.o
.PHONY : src/notes1_stl_types.cpp.o

src/notes1_stl_types.i: src/notes1_stl_types.cpp.i

.PHONY : src/notes1_stl_types.i

# target to preprocess a source file
src/notes1_stl_types.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes1_stl_types.cpp.i
.PHONY : src/notes1_stl_types.cpp.i

src/notes1_stl_types.s: src/notes1_stl_types.cpp.s

.PHONY : src/notes1_stl_types.s

# target to generate assembly for a file
src/notes1_stl_types.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes1_stl_types.cpp.s
.PHONY : src/notes1_stl_types.cpp.s

src/notes2.o: src/notes2.cpp.o

.PHONY : src/notes2.o

# target to build an object file
src/notes2.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes2.cpp.o
.PHONY : src/notes2.cpp.o

src/notes2.i: src/notes2.cpp.i

.PHONY : src/notes2.i

# target to preprocess a source file
src/notes2.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes2.cpp.i
.PHONY : src/notes2.cpp.i

src/notes2.s: src/notes2.cpp.s

.PHONY : src/notes2.s

# target to generate assembly for a file
src/notes2.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes2.cpp.s
.PHONY : src/notes2.cpp.s

src/notes3_iterator_search.o: src/notes3_iterator_search.cpp.o

.PHONY : src/notes3_iterator_search.o

# target to build an object file
src/notes3_iterator_search.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes3_iterator_search.cpp.o
.PHONY : src/notes3_iterator_search.cpp.o

src/notes3_iterator_search.i: src/notes3_iterator_search.cpp.i

.PHONY : src/notes3_iterator_search.i

# target to preprocess a source file
src/notes3_iterator_search.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes3_iterator_search.cpp.i
.PHONY : src/notes3_iterator_search.cpp.i

src/notes3_iterator_search.s: src/notes3_iterator_search.cpp.s

.PHONY : src/notes3_iterator_search.s

# target to generate assembly for a file
src/notes3_iterator_search.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes3_iterator_search.cpp.s
.PHONY : src/notes3_iterator_search.cpp.s

src/notes4_lists.o: src/notes4_lists.cpp.o

.PHONY : src/notes4_lists.o

# target to build an object file
src/notes4_lists.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes4_lists.cpp.o
.PHONY : src/notes4_lists.cpp.o

src/notes4_lists.i: src/notes4_lists.cpp.i

.PHONY : src/notes4_lists.i

# target to preprocess a source file
src/notes4_lists.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes4_lists.cpp.i
.PHONY : src/notes4_lists.cpp.i

src/notes4_lists.s: src/notes4_lists.cpp.s

.PHONY : src/notes4_lists.s

# target to generate assembly for a file
src/notes4_lists.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes4_lists.cpp.s
.PHONY : src/notes4_lists.cpp.s

src/notes5_func_ptrs.o: src/notes5_func_ptrs.cpp.o

.PHONY : src/notes5_func_ptrs.o

# target to build an object file
src/notes5_func_ptrs.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes5_func_ptrs.cpp.o
.PHONY : src/notes5_func_ptrs.cpp.o

src/notes5_func_ptrs.i: src/notes5_func_ptrs.cpp.i

.PHONY : src/notes5_func_ptrs.i

# target to preprocess a source file
src/notes5_func_ptrs.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes5_func_ptrs.cpp.i
.PHONY : src/notes5_func_ptrs.cpp.i

src/notes5_func_ptrs.s: src/notes5_func_ptrs.cpp.s

.PHONY : src/notes5_func_ptrs.s

# target to generate assembly for a file
src/notes5_func_ptrs.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes5_func_ptrs.cpp.s
.PHONY : src/notes5_func_ptrs.cpp.s

src/notes6_func.o: src/notes6_func.cpp.o

.PHONY : src/notes6_func.o

# target to build an object file
src/notes6_func.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes6_func.cpp.o
.PHONY : src/notes6_func.cpp.o

src/notes6_func.i: src/notes6_func.cpp.i

.PHONY : src/notes6_func.i

# target to preprocess a source file
src/notes6_func.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes6_func.cpp.i
.PHONY : src/notes6_func.cpp.i

src/notes6_func.s: src/notes6_func.cpp.s

.PHONY : src/notes6_func.s

# target to generate assembly for a file
src/notes6_func.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_notes.dir/build.make CMakeFiles/cpp_notes.dir/src/notes6_func.cpp.s
.PHONY : src/notes6_func.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cpp_notes"
	@echo "... Tools"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/notes1_stl_types.o"
	@echo "... src/notes1_stl_types.i"
	@echo "... src/notes1_stl_types.s"
	@echo "... src/notes2.o"
	@echo "... src/notes2.i"
	@echo "... src/notes2.s"
	@echo "... src/notes3_iterator_search.o"
	@echo "... src/notes3_iterator_search.i"
	@echo "... src/notes3_iterator_search.s"
	@echo "... src/notes4_lists.o"
	@echo "... src/notes4_lists.i"
	@echo "... src/notes4_lists.s"
	@echo "... src/notes5_func_ptrs.o"
	@echo "... src/notes5_func_ptrs.i"
	@echo "... src/notes5_func_ptrs.s"
	@echo "... src/notes6_func.o"
	@echo "... src/notes6_func.i"
	@echo "... src/notes6_func.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

